pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        // میرور رسمی گوگل برای Maven Central (سریع و پایدار)
        maven { url 'https://maven-central.storage-download.googleapis.com/maven2/' }
        mavenCentral()
    }
}
rootProject.name = "MoeshakMusic"
include ':app'
